services:
  app:
    extends:
      file: docker-compose.build.yml
      service: app
    environment:
      - CONDITION_ID=${CONDITION_ID:?err}
      - STRATEGY=${STRATEGY:?err}
      - CONFIG=${CONFIG:?err}
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    ports:
      - "9090:9008" # Map host port 9090 to container port 9008
    # command: ./run
    command: tail -f /dev/null
